[[repos]]
repo = "local"
hooks = [
  { id = "ruff-check", name = "ruff-check", entry = "ruff check --fix", language = "system", types = [
    "python",
  ] },
  { id = "ruff-format", name = "ruff-format", entry = "ruff format", language = "system", types = [
    "python",
  ] },
  { id = "ty-check", name = "ty-check", entry = "ty check", language = "system", types = [
    "python",
  ] },
]

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-json" },
  { id = "check-toml" },
  { id = "check-symlinks" },
  { id = "check-yaml" },
  { id = "end-of-file-fixer" },
  { id = "no-commit-to-branch", args = [
    "--branch",
    "main",
  ] },
  { id = "trailing-whitespace" },
]
